volumes:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" ## RabbitMQ main port
      - "15672:15672" # Port for RabbitMQ management UI
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  apiservice:
    container_name: apiservice
    build:
      context: .
      dockerfile: BackEnd/LongRunningProcesses.ApiService/Dockerfile
    environment:
      - ConnectionStrings__rabbitmq=amqp://guest:guest@rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - rabbitmq
    restart: on-failure

  workerservice:
    container_name: workerservice
    build:
      context: .
      dockerfile: BackEnd/LongRunningProcesses.WorkerService/Dockerfile
    environment:
      - ConnectionStrings__redis=redis:6379
      - ConnectionStrings__rabbitmq=amqp://guest:guest@rabbitmq:5672
      - services__apiservice__http__0=http://apiservice:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - apiservice
      - redis
      - rabbitmq
    restart: on-failure

  reactapp:
    container_name: reactapp
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - apiservice
    restart: always

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - ./FrontEnd/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./FrontEnd/nginx-proxy/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - reactapp