@LongRunningProcessesApi_HostAddress = http://localhost:5281

POST {{LongRunningProcessesApi_HostAddress}}/api/textprocessor
Content-Type: application/json
Accept: application/json

{
  "text": "Hello, World!"
}

###
