@LongRunningProcessesApi_HostAddress = http://localhost:3000/

POST {{LongRunningProcessesApi_HostAddress}}/api/textprocessor
Content-Type: application/json
Accept: application/json

{
  "text": "Hello, World!",
  "connectionId": "your-connection-id"
}

###
